Add information to help you copy
neontribe/ca-seap pull request #28
Opened 2019-12-17 16:47 UTC by AlinChindea

Fixes #15 

## Description

- Added copy

@neontribe/ca-seap

2020-01-06 16:19 UTC, katjam requested changes
I think the icons is part of another ticket. Probably should put the emoji placeholder back for them.

The slugs need to be written in. I think @AlinChindea fine for you to make some sensible ones and get @roseb04 to approve / check.

2020-01-06 16:19 UTC, katjam commented on src/Copy/BrandCopy.elm
> +            CopyText ""
The slugs are missing.

2020-01-07 14:26 UTC, AlinChindea commented
@roseb04 I've added the slugs - the part that comes at the very end of a URL, and refers to a specific page or post - as per @katjam 's request. Can you check if these are fine?

2020-01-07 14:38 UTC, roseb04 commented
@AlinChindea those look good to me, good to merge

2020-01-07 14:53 UTC, AlinChindea commented
@roseb04 great, I'll add those to the copy file.

2020-01-07 16:18 UTC, katjam approved these changes

2020-01-07 16:18 UTC, merged